/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * INVENTARIO PROBLEMA
 * el inventario al meterle productos no soy capaz de llamar a la instancia sin que apunte a nulo el objeto
 */
package com.allsafe.ui;
//import javax.swing.JFrame;

import com.allsafe.mock.Inventario;
import com.allsafe.model.Producto;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import javax.swing.JOptionPane;



/**
 *
 * @author felixcentenera
 */
public class ModifyProducts extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private Producto pro;
    private Inventario inv = Inventario.getInstance();
    private String Procedencia;
    //private UserManagament user;
    private ProductModifier man;
    
    //private Inventario inv;
    
    
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        

//    HashMap<String, Producto> inventario = new HashMap<>();
//
//    Producto p1 = new Producto("MacBookAirM1", "Apple", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
//    Producto p2 = new Producto("MacBookProM1323", "Apple", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
//    Producto p3 = new Producto("Dell XPS", "Dell", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1);
//    Producto p4 = new Producto("MacBookAirM1323", "Apple323", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
//    Producto p5 = new Producto("MacBookProM123fewf", "Apple23", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
//    Producto p6 = new Producto("Dell XPS323d", "Dell", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1); 
//    Producto p7 = new Producto("MacBookAirM1rtersgh", "Applesrg", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
//    Producto p8 = new Producto("MacBookProM1sregse", "Applesrg", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
//    Producto p9 = new Producto("Dell XPSsrseg", "Dellsrg", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1);
    
//    public ModifyProducts(UserManagament man , String Procedencia) {
//        initComponents();
//        createHomePage();
//       
//        //insertAtributes();
//        user = man;
//        user.setVisible(false);
//        this.setVisible(true);
//        this.Procedencia = Procedencia;
//        this.pro = UserManagament.proCreado;
//        System.out.println(Procedencia);
//        
//        
//    }
    public ModifyProducts(ProductModifier man , Producto prod , String Procedencia) {
        initComponents();
        
       
        //insertAtributes();
        this.man = man;
        man.setVisible(false);
        this.setVisible(true);
        this.Procedencia = Procedencia;
        this.pro = prod;
        createHomePage();
        
        
    }
//    public ModifyProducts() {
//        initComponents();
//        createHomePage();
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JButtomModifyProduct = new javax.swing.JButton();
        JTextTitulo = new javax.swing.JTextField();
        JTextCaracteristicas = new javax.swing.JTextField();
        jTextCategoria = new javax.swing.JTextField();
        JTextLink = new javax.swing.JTextField();
        jTextStock = new javax.swing.JTextField();
        jTextFechaEntrada = new javax.swing.JTextField();
        jTextEstrellas = new javax.swing.JTextField();
        jLabelIMGProducto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabelHomeIcon4 = new javax.swing.JLabel();
        jButtonHomeIcon1 = new javax.swing.JButton();
        jButtonHomeIcon2 = new javax.swing.JButton();
        jButtonHomeIcon4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTimeline8 = new javax.swing.JLabel();
        jLabelTimeline7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonHomeIconsGround5 = new javax.swing.JButton();
        jButtonHomeIconsGround6 = new javax.swing.JButton();
        jButtonHomeIconsGround7 = new javax.swing.JButton();
        jButtonHomeIconsGround8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(6, 40, 73));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        jLabel3.setText("Modificador de Productos ");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel1.setText("Titulo:");

        jLabel2.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel2.setText("Caracteristicas:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel4.setText("Categoria:");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel5.setText("Link Foto:");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel6.setText("Stock:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel7.setText("Fecha Entrada:");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel8.setText("Estrellas:");

        JButtomModifyProduct.setText("Modificar");
        JButtomModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtomModifyProductActionPerformed(evt);
            }
        });

        JTextTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextTituloMouseClicked(evt);
            }
        });

        JTextCaracteristicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextCaracteristicasMouseClicked(evt);
            }
        });

        jTextCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextCategoriaMouseClicked(evt);
            }
        });

        JTextLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextLinkMouseClicked(evt);
            }
        });

        jTextStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextStockMouseClicked(evt);
            }
        });

        jTextFechaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFechaEntradaMouseClicked(evt);
            }
        });

        jTextEstrellas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextEstrellasMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel10.setText("Precio:");

        jTextPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPrecioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(76, 76, 76)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(JButtomModifyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(198, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(JTextTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextCaracteristicas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTextLink, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFechaEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEstrellas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelIMGProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTextCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JTextLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelIMGProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(JButtomModifyProduct)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 770, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1240, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 350, 10));

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 350, 20));
        jPanel3.add(jLabelHomeIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonHomeIcon1.setText("Mi Carrito");
        jButtonHomeIcon1.setBorderPainted(false);
        jButtonHomeIcon1.setContentAreaFilled(false);
        jButtonHomeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeIcon1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonHomeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 120, 60));

        jButtonHomeIcon2.setText("Mi Cuenta");
        jButtonHomeIcon2.setBorderPainted(false);
        jButtonHomeIcon2.setContentAreaFilled(false);
        jPanel3.add(jButtonHomeIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 120, 60));

        jButtonHomeIcon4.setBorderPainted(false);
        jButtonHomeIcon4.setContentAreaFilled(false);
        jPanel3.add(jButtonHomeIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabelTimeline8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 150));
        jPanel4.add(jLabelTimeline7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 630, 140));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1240, 140));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonHomeIconsGround5.setBorderPainted(false);
        jButtonHomeIconsGround5.setContentAreaFilled(false);
        jButtonHomeIconsGround5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeIconsGround5MouseClicked(evt);
            }
        });
        jPanel6.add(jButtonHomeIconsGround5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 40, 40));

        jButtonHomeIconsGround6.setBorderPainted(false);
        jButtonHomeIconsGround6.setContentAreaFilled(false);
        jPanel6.add(jButtonHomeIconsGround6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 40));

        jButtonHomeIconsGround7.setBorderPainted(false);
        jButtonHomeIconsGround7.setContentAreaFilled(false);
        jButtonHomeIconsGround7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeIconsGround7MouseClicked(evt);
            }
        });
        jPanel6.add(jButtonHomeIconsGround7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        jButtonHomeIconsGround8.setBorderPainted(false);
        jButtonHomeIconsGround8.setContentAreaFilled(false);
        jButtonHomeIconsGround8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeIconsGround8MouseClicked(evt);
            }
        });
        jPanel6.add(jButtonHomeIconsGround8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1240, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void createHomePage() {
        try {
            //jLabelImg.setSize(130, 100);
            jLabelHomeIcon4.setIcon(new javax.swing.ImageIcon("Icons/png/AllSafe.png"));
            jButtonHomeIcon4.setIcon(new javax.swing.ImageIcon("Icons/png/search.png"));
            jButtonHomeIcon1.setIcon(new javax.swing.ImageIcon("Icons/png/shopping-cart.png"));
            jButtonHomeIcon2.setIcon(new javax.swing.ImageIcon("Icons/png/user.png"));
            jLabelTimeline8.setIcon(new javax.swing.ImageIcon("Icons/png/TimelineCoversA.jpg"));
            jLabelTimeline7.setIcon(new javax.swing.ImageIcon("Icons/png/TimelineCoversB.jpg"));
            jButtonHomeIconsGround8.setIcon(new javax.swing.ImageIcon("Icons/png/arrowUp.png"));
            jButtonHomeIconsGround7.setIcon(new javax.swing.ImageIcon("Icons/png/ArrowDown.png"));
            jButtonHomeIconsGround5.setIcon(new javax.swing.ImageIcon("Icons/png/home.png"));
            jButtonHomeIconsGround6.setIcon(new javax.swing.ImageIcon("Icons/png/mail.png"));
            
            //******************************************************************************************
            System.out.println(pro.getCategoria());
            jTextCategoria.setText(pro.getCategoria());
            System.out.println(pro.getEstrella());
            jTextEstrellas.setText("" +pro.getEstrella());
            
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            System.out.println( pro.getFechaEntradaTienda().format(formatoCorto));
            jTextFechaEntrada.setText("" + pro.getFechaEntradaTienda().format(formatoCorto));//mirar por que a lo mejor no furula todo lo bien   que se espera
            System.out.println(pro.getStock());
            jTextStock.setText("" + pro.getStock());
            System.out.println(pro.getCaracteristicas());
            JTextCaracteristicas.setText(pro.getCaracteristicas());
            System.out.println(pro.getPrecio());
            jTextPrecio.setText("" + pro.getPrecio());
            System.out.println(pro.getTitulo());
            JTextTitulo.setText(pro.getTitulo());
            System.out.println(pro.getFotografia());
            JTextLink.setText(pro.getFotografia());
            
            jLabelIMGProducto.setIcon(new javax.swing.ImageIcon(pro.getFotografia()));
            
            System.out.println("_________________________________________________");
            
            
            //**********************************************************************************************
//            
//            
//            inventario.put(p1.getTitulo(), p1);
//            inventario.put(p2.getTitulo(), p2);
//            inventario.put(p3.getTitulo(), p3);
//            inventario.put(p4.getTitulo(), p4);
//            inventario.put(p5.getTitulo(), p5);
//            inventario.put(p6.getTitulo(), p6);
//            inventario.put(p7.getTitulo(), p7);
//            inventario.put(p8.getTitulo(), p8);
//            inventario.put(p9.getTitulo(), p9);
//
//            inv.setInventario(inventario);
        
            
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
            JOptionPane.showMessageDialog(null, "Error nos fatan datos", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }
//    public void insertAtributes(){
//        try{
//            System.out.println(pro.getCategoria());
//            jTextCategoria.setText(pro.getCategoria());
//            System.out.println(pro.getEstrella());
//            jTextEstrellas.setText("" +pro.getEstrella());
//            
//            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
//            System.out.println( pro.getFechaEntradaTienda().format(formatoCorto));
//            jTextFechaEntrada.setText("" + pro.getFechaEntradaTienda().format(formatoCorto));//mirar por que a lo mejor no furula todo lo bien   que se espera
//            System.out.println(pro.getStock());
//            jTextStock.setText("" + pro.getStock());
//            System.out.println(pro.getCaracteristicas());
//            JTextCaracteristicas.setText(pro.getCaracteristicas());
//            System.out.println(pro.getPrecio());
//            jTextPrecio.setText("" + pro.getPrecio());
//            System.out.println(pro.getTitulo());
//            JTextTitulo.setText(pro.getTitulo());
//            System.out.println(pro.getFotografia());
//            JTextLink.setText(pro.getFotografia());
//            
//            jLabelIMGProducto.setIcon(new javax.swing.ImageIcon(pro.getFotografia()));
//            
//        
//            System.out.println("INFO: Se han insertado los datos "); 
//        }catch(Exception e){
//            System.out.println("No tenemos todos los valores");
//            JOptionPane.showMessageDialog(null, "Error nos faltan datos", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
//        
//        }
//       
//    }
    
    

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonHomeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeIcon1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Estas entrando en el carrito");
    }//GEN-LAST:event_jButtonHomeIcon1ActionPerformed

    private void JButtomModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtomModifyProductActionPerformed
        // TODO add your handling code here:
        //        jTextCategoria
        //        jTextEstrellas
        //        jTextFechaEntrada
        //        jTextStock
        //        JTextCaracteristicas
        //        jTextPrecio
        //        JTextTitulo
        //        JTextLink

          try{
            //Producto prod = inv.getInventario().get(pro.getTitulo());
            
            
            System.out.println(pro.toString());
            String categoria = jTextCategoria.getText();
            String caracteristicas = JTextCaracteristicas.getText();
            int stock = Integer.parseInt(jTextStock.getText());
            int precio = Integer.parseInt(jTextPrecio.getText());
            String link = JTextLink.getText();
            
            pro.setCaracteristicas(caracteristicas);
            pro.setCategoria(categoria);
            pro.setFotografia(link);
            pro.setStock(stock);
            pro.setPrecio(precio);
            
            System.out.println(inv.getInventario());
            if(!pro.equals(inv.getInventario().get(pro.getTitulo()))){
                inv.getInventario().replace(pro.getTitulo(), pro);
            
                System.out.println("INFO: hemos sobre escrito el producto dado");
            }else{
                System.out.println("INFO:A querido insertar el mismo objeto error");
                JOptionPane.showMessageDialog(null, "No se puede sobreescribir dos veces el mismo objeto", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
              
          
          }catch(Exception e){
              System.out.println("Error " + e.toString());
              JOptionPane.showMessageDialog(null, "Error datos", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        
          }
        

        
    }//GEN-LAST:event_JButtomModifyProductActionPerformed

    private void JTextTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextTituloMouseClicked
        // TODO add your handling code here:
        
        /**
         * jTextCategoria.
            jTextEstrellas
            jTextFechaEntrada
            jTextStock
            JTextCaracteristicas
            jTextPrecio
            JTextTitulo
            JTextLink
         */
        if (JTextTitulo.getText().equals(pro.getTitulo())) {
            JTextTitulo.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            jTextCategoria.setText(pro.getCategoria());

        }

    }//GEN-LAST:event_JTextTituloMouseClicked

    private void JTextCaracteristicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextCaracteristicasMouseClicked
        // TODO add your handling code here:
        if (JTextCaracteristicas.getText().equals(pro.getCaracteristicas())) {
            JTextCaracteristicas.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText("" + pro.getTitulo());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            jTextCategoria.setText(pro.getCategoria());

        }
    }//GEN-LAST:event_JTextCaracteristicasMouseClicked

    private void jTextCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextCategoriaMouseClicked
        // TODO add your handling code here:
        if (jTextCategoria.getText().equals(pro.getCategoria())) {
            jTextCategoria.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
    }//GEN-LAST:event_jTextCategoriaMouseClicked

    private void JTextLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextLinkMouseClicked
        // TODO add your handling code here:
           if (JTextLink.getText().equals(pro.getFotografia())) {
            JTextLink.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            jTextCategoria.setText(pro.getCategoria());

        }
        
    }//GEN-LAST:event_JTextLinkMouseClicked

    private void jTextStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextStockMouseClicked
         //TODO add your handling code here:
        if (jTextStock.getText().equals("" + pro.getStock())) {
            jTextStock.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
         if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            jTextCategoria.setText(pro.getCategoria());

        }
    }//GEN-LAST:event_jTextStockMouseClicked

    private void jTextFechaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFechaEntradaMouseClicked
        // TODO add your handling code here:
        DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
        if (jTextFechaEntrada.getText().equals(pro.getFechaEntradaTienda().format(formatoCorto))) {
            jTextFechaEntrada.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            jTextCategoria.setText(pro.getCategoria());

        }
    }//GEN-LAST:event_jTextFechaEntradaMouseClicked

    private void jTextEstrellasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextEstrellasMouseClicked
        // TODO add your handling code here:
        if (jTextEstrellas.getText().equals("" + pro.getEstrella())) {
            jTextEstrellas.setText("");

        }
         if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getCaracteristicas());

        }
        if (String.valueOf(jTextPrecio.getText()).isEmpty()) {
            jTextPrecio.setText("" + pro.getPrecio());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextLink.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            JTextLink.setText(pro.getCategoria());

        }
    }//GEN-LAST:event_jTextEstrellasMouseClicked

    private void jTextPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPrecioMouseClicked
        // TODO add your handling code here:
        if (jTextPrecio.getText().equals("" + pro.getPrecio())) {
            jTextPrecio.setText("");

        }
        if (String.valueOf(jTextEstrellas.getText()).isEmpty()) {
            jTextEstrellas.setText("" + pro.getEstrella());

        }
        if (String.valueOf(jTextFechaEntrada.getText()).isEmpty()) {
            DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy:HH:mm");
            jTextFechaEntrada.setText(pro.getFechaEntradaTienda().format(formatoCorto));

        }
        if (String.valueOf(jTextStock.getText()).isEmpty()) {
            jTextStock.setText("" + pro.getStock());

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("" + pro.getPrecio());

        }
         if (String.valueOf(JTextTitulo.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getTitulo());

        }
        if (String.valueOf(JTextLink.getText()).isEmpty()) {
            JTextTitulo.setText(pro.getFotografia());

        }
        if (String.valueOf(jTextCategoria.getText()).isEmpty()) {
            JTextLink.setText(pro.getCategoria());

        }
    }//GEN-LAST:event_jTextPrecioMouseClicked

    private void jButtonHomeIconsGround8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeIconsGround8MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Error no se puede ir hacia delante modifique los campos y dele a annadir", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButtonHomeIconsGround8MouseClicked

    private void jButtonHomeIconsGround7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeIconsGround7MouseClicked
        // TODO add your handling code here:
        try {
            //Volvemos hacia atras con el producto
            //***************************************************************************************************
            //volvemos hacia atras habra que modificar el  constructor para volver con el producto
            
            if(Procedencia.equals("ProductModifier")){
                ProductModifier abrirNuevo = new ProductModifier();
                abrirNuevo.setVisible(true);
                this.setVisible(false);

                System.out.println("INFO: Nos vamos al Home");
            }
            if(Procedencia.equals("UserManagament")){
                Home abrirNuevo = new Home();
                abrirNuevo.setVisible(true);
                this.setVisible(false);
            }

            System.out.println("INFO: Nos vamos al Home");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error no hemos encontrado la Pagina " + e.toString(), "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonHomeIconsGround7MouseClicked

    private void jButtonHomeIconsGround5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeIconsGround5MouseClicked
        // TODO add your handling code here:
         try{
             //Volvemos hacia atras con el producto
             //***************************************************************************************************
             //volvemos hacia atras habra que modificar el  constructor para volver con el producto
            UserManagament abrirNuevo = new UserManagament();
            abrirNuevo.setVisible(true);
            this.setVisible(false);
            
            System.out.println("INFO: Nos vamos al Login");
        }catch(Exception e){
            
             JOptionPane.showMessageDialog(null, "Error no hemos encontrado la Pagina "  + e.toString(), "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonHomeIconsGround5MouseClicked

//    private JFrame getFrame() {
//        return this;
//    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModifyProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModifyProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModifyProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModifyProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyProducts().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtomModifyProduct;
    private javax.swing.JTextField JTextCaracteristicas;
    private javax.swing.JTextField JTextLink;
    private javax.swing.JTextField JTextTitulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonHomeIcon1;
    private javax.swing.JButton jButtonHomeIcon2;
    private javax.swing.JButton jButtonHomeIcon4;
    private javax.swing.JButton jButtonHomeIconsGround5;
    private javax.swing.JButton jButtonHomeIconsGround6;
    private javax.swing.JButton jButtonHomeIconsGround7;
    private javax.swing.JButton jButtonHomeIconsGround8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHomeIcon4;
    private javax.swing.JLabel jLabelIMGProducto;
    private javax.swing.JLabel jLabelTimeline7;
    private javax.swing.JLabel jLabelTimeline8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextCategoria;
    private javax.swing.JTextField jTextEstrellas;
    private javax.swing.JTextField jTextFechaEntrada;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextStock;
    // End of variables declaration//GEN-END:variables
}
