/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.allsafe.ui;
//import javax.swing.JFrame;

import com.allsafe.mock.Inventario;
import com.allsafe.model.Producto;
import com.allsafe.service.InventarioService;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;



/**
 *
 * @author felixcentenera
 */
/**
 * **************************************************************************************************************************************
 */

       
public class UserManagament extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public UserManagament() {
        initComponents();
        createHomePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JPanelImgBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTxtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTextCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtextEstrellas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTextStock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTextFecha = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        JLabelBuscar = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelImgCrear = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        JTextCaracteristicas = new javax.swing.JTextField();
        JtextCategoria = new javax.swing.JTextField();
        JTextPrecio = new javax.swing.JTextField();
        JTextLinkImg = new javax.swing.JTextField();
        JTxtStock = new javax.swing.JTextField();
        JTxtDate = new javax.swing.JTextField();
        JTxtStars = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabelHomeIcon4 = new javax.swing.JLabel();
        jButtonHomeIcon1 = new javax.swing.JButton();
        jButtonHomeIcon2 = new javax.swing.JButton();
        jButtonHomeIcon4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTimeline8 = new javax.swing.JLabel();
        jLabelTimeline7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonHomeIconsGround5 = new javax.swing.JButton();
        jButtonHomeIconsGround6 = new javax.swing.JButton();
        jButtonHomeIconsGround7 = new javax.swing.JButton();
        jButtonHomeIconsGround8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(6, 40, 73));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JPanelImgBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Buscar");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Titulo:");

        JTxtTitulo.setForeground(new java.awt.Color(204, 204, 204));
        JTxtTitulo.setText("Escribe el nombre que deseas buscar");
        JTxtTitulo.setBorder(null);
        JTxtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTxtTituloMousePressed(evt);
            }
        });
        JTxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtTituloActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Categoria:");

        JTextCategoria.setForeground(new java.awt.Color(204, 204, 204));
        JTextCategoria.setText("Indique la categoria al que pertenece");
        JTextCategoria.setBorder(null);
        JTextCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextCategoriaMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Estrellas:");

        JtextEstrellas.setForeground(new java.awt.Color(204, 204, 204));
        JtextEstrellas.setText("Indique las Estrellas");
        JtextEstrellas.setBorder(null);
        JtextEstrellas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtextEstrellasMouseClicked(evt);
            }
        });
        JtextEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextEstrellasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Stock:");

        JTextStock.setForeground(new java.awt.Color(204, 204, 204));
        JTextStock.setText("Indique el stock del producto");
        JTextStock.setBorder(null);
        JTextStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextStockMousePressed(evt);
            }
        });
        JTextStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextStockActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Fecha:");

        JTextFecha.setForeground(new java.awt.Color(204, 204, 204));
        JTextFecha.setText("Indique la fecha");
        JTextFecha.setBorder(null);
        JTextFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextFechaMousePressed(evt);
            }
        });

        JLabelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JLabelBuscarMousePressed(evt);
            }
        });

        jLabelImgCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImgCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelImgCrearMousePressed(evt);
            }
        });

        javax.swing.GroupLayout JPanelImgBuscarLayout = new javax.swing.GroupLayout(JPanelImgBuscar);
        JPanelImgBuscar.setLayout(JPanelImgBuscarLayout);
        JPanelImgBuscarLayout.setHorizontalGroup(
            JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTxtTitulo))
                            .addComponent(jSeparator11)
                            .addComponent(jSeparator6)
                            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JtextEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator10)
                            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTextStock, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelImgBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTextFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(JLabelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelImgCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelImgBuscarLayout.setVerticalGroup(
            JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtextEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTextStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(JPanelImgBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelImgBuscarLayout.createSequentialGroup()
                        .addComponent(JLabelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17))
                    .addComponent(jLabelImgCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel9.setText("Crear nuevo producto");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Titulo:");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Caracteristicas:");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("Categoria:");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Precio:");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setText("Link Img");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setText("Stock:");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("Fecha de Entrada");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setText("Estrellas:");

        TxtTitulo.setForeground(new java.awt.Color(204, 204, 204));
        TxtTitulo.setText("Inserte titulo.");
        TxtTitulo.setBorder(null);
        TxtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtTituloMousePressed(evt);
            }
        });
        TxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTituloActionPerformed(evt);
            }
        });

        JTextCaracteristicas.setForeground(new java.awt.Color(204, 204, 204));
        JTextCaracteristicas.setText("Inserte Caracteristicas.");
        JTextCaracteristicas.setBorder(null);
        JTextCaracteristicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextCaracteristicasMousePressed(evt);
            }
        });

        JtextCategoria.setForeground(new java.awt.Color(204, 204, 204));
        JtextCategoria.setText("Inserte categoria");
        JtextCategoria.setBorder(null);
        JtextCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtextCategoriaMousePressed(evt);
            }
        });

        JTextPrecio.setForeground(new java.awt.Color(204, 204, 204));
        JTextPrecio.setText("Inserte precio.");
        JTextPrecio.setBorder(null);
        JTextPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextPrecioMousePressed(evt);
            }
        });

        JTextLinkImg.setForeground(new java.awt.Color(204, 204, 204));
        JTextLinkImg.setText("Inserte Link");
        JTextLinkImg.setBorder(null);
        JTextLinkImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTextLinkImgMousePressed(evt);
            }
        });

        JTxtStock.setForeground(new java.awt.Color(204, 204, 204));
        JTxtStock.setText("Inserte Stock.");
        JTxtStock.setBorder(null);
        JTxtStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTxtStockMousePressed(evt);
            }
        });
        JTxtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtStockActionPerformed(evt);
            }
        });

        JTxtDate.setForeground(new java.awt.Color(204, 204, 204));
        JTxtDate.setText("Inserte fecha de entrada.");
        JTxtDate.setBorder(null);
        JTxtDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTxtDateMousePressed(evt);
            }
        });

        JTxtStars.setForeground(new java.awt.Color(204, 204, 204));
        JTxtStars.setText("Inserte estrellas.");
        JTxtStars.setBorder(null);
        JTxtStars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTxtStarsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTextCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JtextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtTitulo)
                                                .addComponent(JTxtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                            .addComponent(JTextPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(JTextLinkImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JTxtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTxtStars, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTextCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextLinkImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(3, 3, 3)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(4, 4, 4)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(1, 1, 1)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelImgBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JPanelImgBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 990, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1240, 520));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 350, 10));

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 350, 20));
        jPanel3.add(jLabelHomeIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonHomeIcon1.setText("Mi Carrito");
        jButtonHomeIcon1.setBorderPainted(false);
        jButtonHomeIcon1.setContentAreaFilled(false);
        jButtonHomeIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeIcon1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonHomeIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, 120, 60));

        jButtonHomeIcon2.setText("Mi Cuenta");
        jButtonHomeIcon2.setBorderPainted(false);
        jButtonHomeIcon2.setContentAreaFilled(false);
        jPanel3.add(jButtonHomeIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 120, 60));

        jButtonHomeIcon4.setBorderPainted(false);
        jButtonHomeIcon4.setContentAreaFilled(false);
        jPanel3.add(jButtonHomeIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabelTimeline8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 660, 150));
        jPanel4.add(jLabelTimeline7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 630, 140));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1240, 140));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonHomeIconsGround5.setBorderPainted(false);
        jButtonHomeIconsGround5.setContentAreaFilled(false);
        jPanel6.add(jButtonHomeIconsGround5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 40, 40));

        jButtonHomeIconsGround6.setBorderPainted(false);
        jButtonHomeIconsGround6.setContentAreaFilled(false);
        jPanel6.add(jButtonHomeIconsGround6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 40));

        jButtonHomeIconsGround7.setBorderPainted(false);
        jButtonHomeIconsGround7.setContentAreaFilled(false);
        jPanel6.add(jButtonHomeIconsGround7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        jButtonHomeIconsGround8.setBorderPainted(false);
        jButtonHomeIconsGround8.setContentAreaFilled(false);
        jPanel6.add(jButtonHomeIconsGround8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 40, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1240, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Inventario inv = Inventario.getInstance();
    HashMap<String, Producto> inventario = new HashMap<>();

    Producto p1 = new Producto("MacBookAirM1", "Apple", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
    Producto p2 = new Producto("MacBookProM1323", "Apple", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
    Producto p3 = new Producto("Dell XPS", "Dell", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1);
    Producto p4 = new Producto("MacBookAirM1323", "Apple323", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
    Producto p5 = new Producto("MacBookProM123fewf", "Apple23", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
    Producto p6 = new Producto("Dell XPS323d", "Dell", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1); 
    Producto p7 = new Producto("MacBookAirM1rtersgh", "Applesrg", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookAirM1.png", 1);
    Producto p8 = new Producto("MacBookProM1sregse", "Applesrg", "Portatiles", 1000, "Img/laptops/macbook/appleMacbookProM1.png", 1);
    Producto p9 = new Producto("Dell XPSsrseg", "Dellsrg", "Portatiles", 1000, "Img/laptops/dell/dellXps13.png", 1);
    
    
    

    private void createHomePage() {
        try {
            //jLabelImg.setSize(130, 100);
            jLabelHomeIcon4.setIcon(new javax.swing.ImageIcon("Icons/png/AllSafe.png"));
            jButtonHomeIcon4.setIcon(new javax.swing.ImageIcon("Icons/png/search.png"));
            jButtonHomeIcon1.setIcon(new javax.swing.ImageIcon("Icons/png/shopping-cart.png"));
            jButtonHomeIcon2.setIcon(new javax.swing.ImageIcon("Icons/png/user.png"));
            jLabelTimeline8.setIcon(new javax.swing.ImageIcon("Icons/png/TimelineCoversA.jpg"));
            jLabelTimeline7.setIcon(new javax.swing.ImageIcon("Icons/png/TimelineCoversB.jpg"));
            jButtonHomeIconsGround8.setIcon(new javax.swing.ImageIcon("Icons/png/arrowUp.png"));
            jButtonHomeIconsGround7.setIcon(new javax.swing.ImageIcon("Icons/png/ArrowDown.png"));
            jButtonHomeIconsGround5.setIcon(new javax.swing.ImageIcon("Icons/png/home.png"));
            jButtonHomeIconsGround6.setIcon(new javax.swing.ImageIcon("Icons/png/mail.png"));
            jLabelImgCrear.setIcon(new javax.swing.ImageIcon("Icons/png/Annadir.png"));
            JLabelBuscar.setIcon(new javax.swing.ImageIcon("Icons/png/Buscar.png"));
            
            
            inventario.put(p1.getTitulo(), p1);
            inventario.put(p2.getTitulo(), p2);
            inventario.put(p3.getTitulo(), p3);
            inventario.put(p4.getTitulo(), p4);
            inventario.put(p5.getTitulo(), p5);
            inventario.put(p6.getTitulo(), p6);
            inventario.put(p7.getTitulo(), p7);
            inventario.put(p8.getTitulo(), p8);
            inventario.put(p9.getTitulo(), p9);

            inv.setInventario(inventario);

        
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonHomeIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeIcon1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Estas entrando en el carrito");
    }//GEN-LAST:event_jButtonHomeIcon1ActionPerformed

    private void JTxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtTituloActionPerformed

    private void JtextEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextEstrellasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextEstrellasActionPerformed

    private void JTextStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextStockActionPerformed

    private void JTxtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtStockActionPerformed
    /**
     *    private javax.swing.JLabel JLabelBuscar;
    private javax.swing.JPanel ;
   
    
    p
    p
    p
    private javax.swing.JTextField JTxtStock;
    
    private javax.swing.JTextField TxtTitulo;
     */
    private void TxtTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTituloMousePressed
        // TODO add your handling code here:if(UserName.getText().equals("Ingrese su nombre de usuario")){
        if (TxtTitulo.getText().equals("Inserte titulo.")) {
            TxtTitulo.setText("");
            TxtTitulo.setForeground(Color.black);
        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Link");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
        
    }//GEN-LAST:event_TxtTituloMousePressed

    private void JTextCaracteristicasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextCaracteristicasMousePressed
        // TODO add your handling code here:
         if (JTextCaracteristicas.getText().equals("Inserte Caracteristicas.")) {
            JTextCaracteristicas.setText("");
            JTextCaracteristicas.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
    }//GEN-LAST:event_JTextCaracteristicasMousePressed

    private void JtextCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtextCategoriaMousePressed
        // TODO add your handling code here:
        if (JtextCategoria.getText().equals("Inserte categoria")) {
            JtextCategoria.setText("");
            JtextCategoria.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
        
    }//GEN-LAST:event_JtextCategoriaMousePressed

    private void JTextPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextPrecioMousePressed
        // TODO add your handling code here:
        if (JTextPrecio.getText().equals("Inserte precio.")) {
            JTextPrecio.setText("");
            JTextPrecio.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
    }//GEN-LAST:event_JTextPrecioMousePressed

    private void JTextLinkImgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextLinkImgMousePressed
        // TODO add your handling code here:
        if (JTextLinkImg.getText().equals("Inserte Link")) {
            JTextLinkImg.setText("");
            JTextLinkImg.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
        
    }//GEN-LAST:event_JTextLinkImgMousePressed

    private void JTxtStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtStockMousePressed
        // TODO add your handling code here:
     
        if (JTxtStock.getText().equals("Inserte Stock.")) {
            JTxtStock.setText("");
            JTxtStock.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
    }//GEN-LAST:event_JTxtStockMousePressed

    private void JTxtDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtDateMousePressed
        // TODO add your handling code here:
        if (JTxtDate.getText().equals("Inserte fecha de entrada.")) {
            JTxtDate.setText("");
            JTxtDate.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStars.getText()).isEmpty()) {
            JTxtStars.setText("Inserte estrellas.");
            JTxtStars.setForeground(Color.gray);

        }
    }//GEN-LAST:event_JTxtDateMousePressed

    private void JTxtStarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtStarsMouseClicked
        // TODO add your handling code here:
        if (JTxtStars.getText().equals("Inserte estrellas.")) {
            JTxtStars.setText("");
            JTxtStars.setForeground(Color.black);
        }
        if (String.valueOf(TxtTitulo.getText()).isEmpty()) {
            TxtTitulo.setText("Inserte titulo.");
            TxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCaracteristicas.getText()).isEmpty()) {
            JTextCaracteristicas.setText("Inserte Caracteristicas.");
            JTextCaracteristicas.setForeground(Color.gray);

        }
        if (String.valueOf(JtextCategoria.getText()).isEmpty()) {
            JtextCategoria.setText("Inserte categoria");
            JtextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextPrecio.getText()).isEmpty()) {
            JTextPrecio.setText("Inserte precio.");
            JTextPrecio.setForeground(Color.gray);

        }
        if (String.valueOf(JTextLinkImg.getText()).isEmpty()) {
            JTextLinkImg.setText("Inserte Link");
            JTextLinkImg.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtStock.getText()).isEmpty()) {
            JTxtStock.setText("Inserte Stock.");
            JTxtStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTxtDate.getText()).isEmpty()) {
            JTxtDate.setText("Inserte fecha de entrada.");
            JTxtDate.setForeground(Color.gray);

        }
        
    }//GEN-LAST:event_JTxtStarsMouseClicked

    private void TxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTituloActionPerformed

    private void jLabelImgCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImgCrearMousePressed
        // TODO add your handling code here:

//            private javax.swing.JTextField JTextCaracteristicas;
//            private javax.swing.JTextField JTextLinkImg;
//            private javax.swing.JTextField JTextPrecio;
//            private javax.swing.JTextField JTxtDate;
//            private javax.swing.JTextField JTxtStars;
//            private javax.swing.JTextField JTxtStock;
//            private javax.swing.JTextField JtextCategoria;
//            private javax.swing.JTextField TxtTitulo;
        try{
            String caracteristicas = JTextCaracteristicas.getText();
            String link = JTextLinkImg.getText();
            int precio = Integer.parseInt(JTextPrecio.getText());
            String fecha1txt = JTxtDate.getText();
            
            DateTimeFormatter JEFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            LocalDateTime local_date = LocalDateTime.parse(fecha1txt, JEFormatter);
            System.out.println(local_date);

            int estrellas = Integer.parseInt(JTxtStars.getText()); 
            int Stock = Integer.parseInt(JTxtStock.getText());
            String Categoria = JtextCategoria.getText();
            String Titulo = TxtTitulo.getText();
            
            InventarioService.CreateProduct(Titulo, caracteristicas, Categoria, precio, Categoria, Stock, inv);
            
        }catch(Exception e){
            
            System.out.println("INFO: Excepcion definida por el usuario , datos mal intrducidos al intentar crear un nuevo objeto");
            JOptionPane.showMessageDialog(null, "Se ha introducion mal alguno de los campos intetelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
        
        }
            
            
        
    }//GEN-LAST:event_jLabelImgCrearMousePressed

    private void JTxtTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTxtTituloMousePressed
        // TODO add your handling code here:
        if (JTxtTitulo.getText().equals("Escribe el nombre que deseas buscar")) {
            JTxtTitulo.setText("");
            JTxtTitulo.setForeground(Color.black);
        }
        if (String.valueOf(JTextCategoria.getText()).isEmpty()) {
            JTextCategoria.setText("Indique la categoria al que pertenece");
            JTextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JtextEstrellas.getText()).isEmpty()) {
            JtextEstrellas.setText("Indique las Estrellas");
            JtextEstrellas.setForeground(Color.gray);

        }
        if (String.valueOf(JTextStock.getText()).isEmpty()) {
            JTextStock.setText("Indique el stock del producto");
            JTextStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTextFecha.getText()).isEmpty()) {
            JTextFecha.setText("Indique la fecha");
            JTextFecha.setForeground(Color.gray);

        }
        
        
    }//GEN-LAST:event_JTxtTituloMousePressed

    private void JTextCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextCategoriaMousePressed
        // TODO add your handling code here:
        if (JTextCategoria.getText().equals("Indique la categoria al que pertenece")) {
            JTextCategoria.setText("");
            JTextCategoria.setForeground(Color.black);
        }
        if (String.valueOf(JTxtTitulo.getText()).isEmpty()) {
            JTxtTitulo.setText("Escribe el nombre que deseas buscar");
            JTxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JtextEstrellas.getText()).isEmpty()) {
            JtextEstrellas.setText("Indique las Estrellas");
            JtextEstrellas.setForeground(Color.gray);

        }
        if (String.valueOf(JTextStock.getText()).isEmpty()) {
            JTextStock.setText("Indique el stock del producto");
            JTextStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTextFecha.getText()).isEmpty()) {
            JTextFecha.setText("Indique la fecha");
            JTextFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_JTextCategoriaMousePressed

    private void JtextEstrellasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtextEstrellasMouseClicked
        // TODO add your handling code here:
        if (JtextEstrellas.getText().equals("Indique las Estrellas")) {
            JtextEstrellas.setText("");
            JtextEstrellas.setForeground(Color.black);
        }
        if (String.valueOf(JTxtTitulo.getText()).isEmpty()) {
            JTxtTitulo.setText("Escribe el nombre que deseas buscar");
            JTxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCategoria.getText()).isEmpty()) {
            JTextCategoria.setText("Indique la categoria al que pertenece");
            JTextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JTextStock.getText()).isEmpty()) {
            JTextStock.setText("Indique el stock del producto");
            JTextStock.setForeground(Color.gray);

        }
        if (String.valueOf(JTextFecha.getText()).isEmpty()) {
            JTextFecha.setText("Indique la fecha");
            JTextFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_JtextEstrellasMouseClicked

    private void JTextStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextStockMousePressed
        // TODO add your handling code here:
        if (JTextStock.getText().equals("Indique el stock del producto")) {
            JTextStock.setText("");
            JTextStock.setForeground(Color.black);
        }
        if (String.valueOf(JTxtTitulo.getText()).isEmpty()) {
            JTxtTitulo.setText("Escribe el nombre que deseas buscar");
            JTxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCategoria.getText()).isEmpty()) {
            JTextCategoria.setText("Indique la categoria al que pertenece");
            JTextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JtextEstrellas.getText()).isEmpty()) {
            JtextEstrellas.setText("Indique las Estrellas");
            JtextEstrellas.setForeground(Color.gray);

        }
        if (String.valueOf(JTextFecha.getText()).isEmpty()) {
            JTextFecha.setText("Indique la fecha");
            JTextFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_JTextStockMousePressed

    private void JTextFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextFechaMousePressed
        // TODO add your handling code here:
        if (JTextFecha.getText().equals("Indique la fecha")) {
            JTextFecha.setText("");
            JTextFecha.setForeground(Color.black);
        }
        if (String.valueOf(JTxtTitulo.getText()).isEmpty()) {
            JTxtTitulo.setText("Escribe el nombre que deseas buscar");
            JTxtTitulo.setForeground(Color.gray);

        }
        if (String.valueOf(JTextCategoria.getText()).isEmpty()) {
            JTextCategoria.setText("Indique la categoria al que pertenece");
            JTextCategoria.setForeground(Color.gray);

        }
        if (String.valueOf(JtextEstrellas.getText()).isEmpty()) {
            JtextEstrellas.setText("Indique las Estrellas");
            JtextEstrellas.setForeground(Color.gray);

        }
        if (String.valueOf(JTextStock.getText()).isEmpty()) {
            JTextStock.setText("Indique el stock del producto");
            JTextStock.setForeground(Color.gray);
        }
    }//GEN-LAST:event_JTextFechaMousePressed

    private void JLabelBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelBuscarMousePressed
        // TODO add your handling code here:
        if ((!String.valueOf(JTxtTitulo.getText()).isEmpty()) && !(JTxtTitulo.getText().equals("Escribe el nombre que deseas buscar"))){
            try{
                
                String Nombre = JTxtTitulo.getText();
                String Clave = InventarioService.findProductwithName(Nombre, inv);
                System.out.println("INFO: Hemos encontrado el producto en el inventario pasamos a la pantalla de modificacion de producto");
                
                //Buscamelo y si esta y no me arrojas excepcion habreme la nueva pantalla
            }catch(Exception e){
                
                System.out.println("INFO: No se h encontrado producto dentro del inventario, Excepcion " + e.toString());
                JOptionPane.showMessageDialog(null, "No se ha encontrado el producto en el inventario intentelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JTxtTitulo.setText("Escribe el nombre que deseas buscar");
            }
            
        }else if((!String.valueOf(JTextFecha.getText()).isEmpty()) && !(JTextFecha.getText().equals("Escribe el nombre que deseas buscar"))){
            try{
                String fecha1txt = JTextFecha.getText();
                DateTimeFormatter JEFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDateTime local_date = LocalDateTime.parse(fecha1txt, JEFormatter);
                
                InventarioService.findProductwithFecha(local_date, inv);
                
                //Pasamos al nuevo JFrame
                
                System.out.println("INFO: hemos pasado al nuevo JFrame");
                
            
            }catch(Exception e){
                
                System.out.println("INFO: No se h encontrado producto dentro del inventario, Excepcion " + e.toString());
                JOptionPane.showMessageDialog(null, "No se ha encontrado el producto en el inventario intentelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JTxtTitulo.setText("Indique la fecha");
            
            }
        
        }else if((!String.valueOf(JtextEstrellas.getText()).isEmpty()) && !(JtextEstrellas.getText().equals("Escribe el nombre que deseas buscar"))){
        
            try{
                int estrellas = Integer.parseInt(JtextEstrellas.getText());
                ArrayList<String> ProductKeys = new ArrayList<>(InventarioService.findProductwithStars(estrellas, inv));
                
                //Llamamos a la nueva pagina y hacemos lo que haya que hacer
                
                System.out.println("INFO: Hemos pasado al nuevo JFrame");
                
            }catch(Exception e){
                System.out.println("INFO: No se ha encontrado producto dentro del inventario, " + e.toString());
                JOptionPane.showMessageDialog(null, "No se ha encontrado el producto en el inventario intentelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JTxtTitulo.setText("Indique la categoria al que pertenece");
            
            }
        
        }else if((!String.valueOf(JTextStock.getText()).isEmpty()) && !(JTextStock.getText().equals("Escribe el nombre que deseas buscar")))
            try{
                int Stock = Integer.parseInt(JTextStock.getText());
                ArrayList<String> ProductKeys = new ArrayList<>(InventarioService.findProductwithStock(Stock, inv));
                
                System.out.println("INFO: Hemos pasado al nuevo JFrame");
            }catch(Exception e){
                System.out.println("INFO: No se ha encontrado producto dentro del inventario, " + e.toString());
                JOptionPane.showMessageDialog(null, "No se ha encontrado el producto en el inventario intentelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JTxtTitulo.setText("Indique la categoria al que pertenece");
            
        }else if((!String.valueOf(JTextCategoria.getText()).isEmpty()) && !(JTextCategoria.getText().equals("Escribe el nombre que deseas buscar")))
            try{
                String Categoria = JTextCategoria.getText();
                ArrayList<String> ProductKeys = new ArrayList<>(InventarioService.findProductwithCategory(Categoria, inv));
                //hacemos lo que haga falta en este jText
                
                System.out.println("INFO: Hemos pasado al nuevo JFrame");
                
            }catch(Exception e){
                System.out.println("INFO: No se ha encontrado producto dentro del inventario, " + e.toString());
                JOptionPane.showMessageDialog(null, "No se ha encontrado el producto en el inventario intentelo de nuevo", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
                JTxtTitulo.setText("Indique la categoria al que pertenece");
            
            }
        else{
            
            System.out.println("INFO: No se han insertado bien los datos");
            JOptionPane.showMessageDialog(null, "No se han insertado bien los datos en la pantalla", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            
            JTextStock.setText("Indique el stock del producto");
            JtextEstrellas.setText("Indique las Estrellas");
            JTextCategoria.setText("Indique la categoria al que pertenece");
            JTextFecha.setText("Indique la fecha");
            JTxtTitulo.setText("Escribe el nombre que deseas buscar");
        }
    }//GEN-LAST:event_JLabelBuscarMousePressed

//    private JFrame getFrame() {
//        return this;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBuscar;
    private javax.swing.JPanel JPanelImgBuscar;
    private javax.swing.JTextField JTextCaracteristicas;
    private javax.swing.JTextField JTextCategoria;
    private javax.swing.JTextField JTextFecha;
    private javax.swing.JTextField JTextLinkImg;
    private javax.swing.JTextField JTextPrecio;
    private javax.swing.JTextField JTextStock;
    private javax.swing.JTextField JTxtDate;
    private javax.swing.JTextField JTxtStars;
    private javax.swing.JTextField JTxtStock;
    private javax.swing.JTextField JTxtTitulo;
    private javax.swing.JTextField JtextCategoria;
    private javax.swing.JTextField JtextEstrellas;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonHomeIcon1;
    private javax.swing.JButton jButtonHomeIcon2;
    private javax.swing.JButton jButtonHomeIcon4;
    private javax.swing.JButton jButtonHomeIconsGround5;
    private javax.swing.JButton jButtonHomeIconsGround6;
    private javax.swing.JButton jButtonHomeIconsGround7;
    private javax.swing.JButton jButtonHomeIconsGround8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHomeIcon4;
    private javax.swing.JLabel jLabelImgCrear;
    private javax.swing.JLabel jLabelTimeline7;
    private javax.swing.JLabel jLabelTimeline8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
